### ISSUE TITLE
Google meet.

### ISSUE THREAD

**Issue by martinfarnanequal1** [ftassy/GCalTab#7]
Hi, 
I am trying out the GCalTab, one small issue I have is that when I open a google meeting it does not have access to the mic and video. The tab opens as a new tab in thunderbird. Have you figured out how to enable the access? 

The workaround is to right-click the mouse button and open the link chrome, but I think it should be possible to just click on the meeting and it will open a new tab in thunderbird with the right permissions. 

Thanks,
Martin

**Comment by ftassy** [comment]
Hi Martin,  

Thanks for reporting the issue 🙂  

The issue you describe here is not specific to GCalTab, and it is the expected behavior from Thunderbird.  
Indeed, as a mail client, Thunderbird does not implement the permission popups that are supposed to grant access to microphone and camera.  

Therefore, the most recommendable practice is to stick with your workaround and open Google Meet in a web browser. It is also a good idea because web browsers allow fine-tuning of browsing parameters, cookies, and so on... while Thunderbird won't have all options available.  

I hope this helps,  
Florent
